"""add nullable Fallse

Revision ID: 5eb0a37f95d9
Revises: 966fd12993a1
Create Date: 2023-02-25 20:17:29.754813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb0a37f95d9'
down_revision = '966fd12993a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
