"""фÐadd related_names

Revision ID: 966fd12993a1
Revises: 9fc379c2bbeb
Create Date: 2023-02-25 15:51:18.728451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966fd12993a1'
down_revision = '9fc379c2bbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
