"""Ðfix

Revision ID: 9dd84009d1f6
Revises: 5eb0a37f95d9
Create Date: 2023-02-25 20:37:07.420250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd84009d1f6'
down_revision = '5eb0a37f95d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Translate', 'russian_expression',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('Translate', 'english_expression',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
